FROM python:3
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
COPY brainstreamer brainstreamer

ENV MQ_URL rabbitmq://mq:5672
CMD python -m brainstreamer.parsers run-parser ${PARSER} ${MQ_URL}
