FROM python:3
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
COPY brainstreamer brainstreamer

ENV MQ_URL rabbitmq://mq:5672
ENV DB_URL mongodb://db:27017
CMD python -m brainstreamer.saver run-saver ${DB_URL} ${MQ_URL}
