FROM python:3
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
COPY brainstreamer brainstreamer

ENV HOST 0.0.0.0
ENV PORT 5000
ENV DB_URL mongodb://db:27017
CMD python -m brainstreamer.api run-server -h ${HOST} -p ${PORT} -d ${DB_URL}
