FROM python:3
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
COPY brainstreamer brainstreamer

ENV HOST 0.0.0.0
ENV PORT 8080
ENV API_HOST 127.0.0.1
ENV API_PORT 5000
CMD python -m brainstreamer.gui run-server -h ${HOST} -p ${PORT} -H ${API_HOST} -P ${API_PORT}
