FROM python:3
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
COPY brainstreamer brainstreamer

ENV HOST 0.0.0.0
ENV PORT 8000
ENV MQ_URL rabbitmq://mq:5672
CMD python -m brainstreamer.server run-server -h ${HOST} -p ${PORT} ${MQ_URL}
